---
title: "Adding primers from metapr2"
author: "Daniel Vaulot"
date: '`r format(Sys.time(), "%d %m %Y")`'
header-includes:
   - \usepackage{color, fancyvrb}
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
    toc: yes
    toc_depth: 3
    number_sections : yes
  pdf_document: 
    toc: yes
    toc_depth: 3
    number_sections : yes
  rmdformats::readthedown:
    highlight: kate
    number_sections : yes    
---

# Goal
* Find primers from metapr2 that are not in the PR2 primer database
    

# Initialize
Load the variables common to the different scripts and the necessary libraries

```{r init, eval=TRUE, message=FALSE, warning=FALSE}

# Libraries for bioinfo ----------------------------------------------------

  library("Biostrings")

# Libraries tidyr ---------------------------------------------------------

  library("ggplot2")
  theme_set(theme_light())
  library("dplyr") 
  library("tibble")
  library("rio")
  library("purrr")
  library("forcats")
  library("lubridate")
  library("stringr")

# Libraries dvutils and pr2database -------------------------------------------------------
  if(any(grepl("package:dvutils", search()))) detach("package:dvutils", unload=TRUE)
  library("dvutils")


# Options for knitting the report -------------  
  
  library(knitr)
  library(rmdformats)
  library(kableExtra) 

  knitr::opts_chunk$set(fig.width=8, 
                        fig.height=6, 
                        eval=TRUE, 
                        cache=TRUE,
                        echo=TRUE,
                        prompt=FALSE,
                        tidy=TRUE,
                        comment=NA,
                        message=FALSE,
                        warning=FALSE)
  opts_knit$set(width=90)
  options(max.print="500")  
  options(knitr.kable.NA = '')
```


# Read primer file


## Build the primer set Table

Only keep the 18S primers with V region

```{r}

# Read from local database
pr2_db <- db_info("pr2_google")
pr2_db_con <- db_connect(pr2_db)

primers <- tbl(pr2_db_con, "pr2_primers") %>% 
  collect()
primer_sets_all <- tbl(pr2_db_con, "pr2_primer_sets") %>% 
  collect()

disconnect <- db_disconnect(pr2_db_con)


  
  primer_sets <- primer_sets_all %>% 
    filter(gene == "18S rRNA")
    
  

primer_sets <- primer_sets %>% 
  left_join(select(primers, 
                   primer_id, 
                   fwd_name=name,
                   fwd_seq=sequence, 
                   fwd_start_yeast= start_yeast, 
                   fwd_end_yeast= end_yeast), 
            by = c("fwd_id" = "primer_id")) %>% 
  left_join(select(primers, 
                 primer_id, 
                 rev_name=name,
                 rev_seq=sequence, 
                 rev_start_yeast= start_yeast, 
                 rev_end_yeast= end_yeast), 
          by = c("rev_id" = "primer_id")) %>% 
  mutate(length_yeast = rev_end_yeast - fwd_start_yeast + 1) %>% 
  select(gene_region, specificity, 
         primer_set_id, primer_set_name,
         contains("fwd"), 
         contains("rev"),
         length_yeast, 
         reference:remark) %>%
  select(-fwd_id, -rev_id) %>% 
  arrange(gene_region,  fwd_start_yeast, rev_start_yeast) %>% 
  mutate(specific = ifelse(is.na(specificity), "general", "specific")) %>% 
  relocate(specific, .before = specificity)
  

```

# Metapr2 database primers

## Read the data

```{r}
  datasets <- metapr2_export_datasets() %>% 
     filter(gene == "18S rRNA") 
```

## Make the primer table

```{r}
 primers_fwd <- datasets %>% 
  select(name=primer_fwd_name, sequence=primer_fwd_seq, reference = paper_reference,  
         doi = paper_doi, specificity = primer_specificity) %>% 
  filter(!is.na(sequence),
         !(sequence %in% primers$sequence))  %>%
  arrange(sequence) %>% 
  distinct()  %>% 
  mutate(direction = "fwd")
  
 primers_rev <- datasets  %>% 
  select(name=primer_rev_name, sequence=primer_rev_seq, reference = paper_reference,  
         doi = paper_doi, specificity = primer_specificity) %>% 
  filter(!is.na(sequence),
         !(sequence %in% primers$sequence))  %>%
  arrange(sequence) %>% 
  distinct()  %>% 
  mutate(direction = "rev") 
  
 primers_metapr2 <- bind_rows(primers_fwd, primers_rev)
 
 export(primers_metapr2, "../output/primers_metapr2.xlsx")

```

## Make the primer table

```{r}
 primer_sets_metapr2 <- datasets %>% 
  select(primer_fwd_name,primer_fwd_seq,primer_rev_name,primer_rev_seq) %>% 
  distinct() %>% 
  filter(!is.na(primer_fwd_name)) %>% 
  arrange(primer_fwd_seq, primer_rev_seq) %>% 
# Remove all primers sets already in primer database
  left_join(primer_sets, c("primer_fwd_seq" = "fwd_seq","primer_rev_seq"= "rev_seq")) %>% 
  filter(is.na(fwd_name) ) %>% 
  select(primer_fwd_name,primer_fwd_seq,primer_rev_name,primer_rev_seq) %>% 
  left_join(datasets) %>% 
# Get the id of the forward primer
  left_join(select(primers, fwd_id = primer_id, sequence), c("primer_fwd_seq" = "sequence")) %>% 
# Get the id of the forward primer
  left_join(select(primers, rev_id = primer_id, sequence), c("primer_rev_seq" = "sequence"))

export(primer_sets_metapr2, "../output/primer_sets_metapr2.xlsx")


```

